apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 175534384170.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
        ports:
        - containerPort: 3306
        imagePullPolicy: IfNotPresent