apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 175534384170.dkr.ecr.us-east-1.amazonaws.com/assignment2/mysql:latest
    ports:
    - containerPort: 3306
    imagePullPolicy: IfNotPresent