apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: employees
spec:
  containers:
  - name: web-app
    image: 175534384170.dkr.ecr.us-east-1.amazonaws.com/assignment2/web-app:latest
    ports:
    - containerPort: 80