apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app
        image: 175534384170.dkr.ecr.us-east-1.amazonaws.com/assignment2/web-app:latest
        ports:
        - containerPort: 80