apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: webapp-ns
spec:
  selector:
    app: employees
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort