name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
            
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Test AWS Credentials
        run: |
          echo "Running AWS sts get-caller-identity"
          aws sts get-caller-identity 
          
      - name: Login to Amazon ECR
        run: |
          echo "Logging in to ECR"
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com || exit 1

      - name: Check if ECR Repositories Exist and Create If Needed
        run: |
          echo "Checking if repositories exist"
          aws ecr describe-repositories --repository-names assignment2/web-app --region ${{ secrets.AWS_REGION }} || aws ecr create-repository --repository-name assignment2/web-app --region ${{ secrets.AWS_REGION }}
          aws ecr describe-repositories --repository-names assignment2/mysql --region ${{ secrets.AWS_REGION }} || aws ecr create-repository --repository-name assignment2/mysql --region ${{ secrets.AWS_REGION }}
        
      - name: Build Docker Images
        run: |
          echo "Building web app image"
          docker build -t assignment2-web-app -f Dockerfile .
          echo "Building MySQL image"
          docker build -t assignment2-mysql -f Dockerfile_mysql .

      - name: Tag and Push to Amazon ECR
        run: |
          echo "Tagging web app image"
          docker tag assignment2-web-app:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/assignment2/web-app:latest
          echo "Tagging MySQL image"
          docker tag assignment2-mysql:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/assignment2/mysql:latest
          echo "Pushing web app image to ECR"
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/assignment2/web-app:latest
          echo "Pushing MySQL image to ECR"
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/assignment2/mysql:latest