name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Test AWS credentials
      - name: Test AWS Credentials
        run: |
          echo "Running AWS sts get-caller-identity"
          aws sts get-caller-identity

      # Step 4: Add SSH Private Key
      - name: Add SSH Private Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 6: Initialize Terraform
      - name: Terraform Init
        run: |
          cd terraform-k8s
          terraform init

      # Step 7: Run Terraform Plan
      - name: Terraform Plan
        run: |
          cd terraform-k8s
          terraform plan

      # Step 8: Apply Terraform Changes
      - name: Terraform Apply
        run: |
          cd terraform-k8s
          terraform apply -auto-approve

  terraform-destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Run only on manual trigger
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: |
          cd terraform-k8s
          terraform init

      # Step 5: Destroy Terraform Resources
      - name: Terraform Destroy
        run: |
          cd terraform-k8s
          terraform destroy -auto-approve